### ISSUE TITLE
[DOCS] MkDocs doesn't render $$ equations

### ISSUE THREAD

**Issue by pilot7747** [Toloka/crowd-kit#106]
### Problem description

It seems that MkDocs doesn't render all the equations that are written in a format
```
$$
<some_equation>
$$
```

Like [here](https://crowd-kit.readthedocs.io/en/latest/classification/#crowdkit.aggregation.classification.DawidSkene) it doesn't render `$$ \operatorname{Pr}(z_j = c) = p[c], $$`.

### Documentation links

https://crowd-kit.readthedocs.io/en/latest/classification/#crowdkit.aggregation.classification.DawidSkene

**Comment by dustalov** [comment]
It renders `$e = mc^2 + AI$ but not $$e = mc^2 + AI$$, is that right?

**Comment by dustalov** [comment]
It renders equations like `$e = mc^2 + AI$` but not like `$$e = mc^2 + AI$$`, is that right?

**Comment by pilot7747** [comment]
Yep
