### ISSUE TITLE
[BUG] MajorityVote() doesn't return what expected

### ISSUE THREAD

**Issue by LydiaMak** [Toloka/crowd-kit#108]
### Observed behavior

MajorityVote() doesn't return the result of the most workers. 

### Expected behavior

MajorityVote() to return the result of the most workers.

### Python Version

3.11

### Crowd-Kit Version

1.2.1

### Example code

```Python
mv = MajorityVote()
resultmv = mv.fit_predict(df_crowd)
```

**Comment by pilot7747** [comment]
@LydiaMak Could you provide an example please?

**Comment by LydiaMak** [comment]
Ok it is solved. It was a bug in my code. However, I have a questions. When there is a tie between the different workers, how is the final result selected?
