### ISSUE TITLE
[FEATURE] Version 1.4.0 release

### ISSUE THREAD

**Issue by shenxiangzhuang** [Toloka/crowd-kit#121]
### Problem description

Shall we release a new version for these changes after 1.3.0?

### Feature description

Release a new version.

**Comment by pilot7747** [comment]
why not? @dustalov wdyt?

**Comment by dustalov** [comment]
No reason not to. I'll do it today later. I believe that it should be 1.3.1, though.

**Comment by shenxiangzhuang** [comment]
> No reason not to. I'll do it today later. I believe that it should be 1.3.1, though.

Very glad to hear that! I'm just wondering why we should use 1.3.1 instead of 1.4.0. Some new functionality has been added, and bumping the minor version seems fine according to https://semver.org/ (2. MINOR version when you add functionality in a backward compatible manner).

**Comment by dustalov** [comment]
I double-checked the commit history and noticed that we had a lot of significant changes, including a switch to uv, some dependency version freezes, etc. The 1.4.0 is now on PyPI.

@shenxiangzhuang: could you please check if we can release 1.4.1 with the relaxed requirement to `attrs`?

**Comment by shenxiangzhuang** [comment]
Ok. I'll check it later.
