### ISSUE TITLE
how to deal with features in pairwaise comparison models?

### ISSUE THREAD

**Issue by amine-boukriba** [Toloka/crowd-kit#14]
I am working on a dataset of ATP (Association of Tennis Professionals - men only) tennis games over several years. I want to predict the outcome of tennis so one way to do that is using a Bradley-Terry model which is a probability model I am asking about how to do feature selection or feature engineering( I am not talking about domain knowledge FE) or preprocessing that must be applied before training the model

**Comment by dustalov** [comment]
Hi, thank you for reaching us. Bradley-Terry model and many related models take into account only the comparisons between objects, but not their properties. There are such methods as factorBT that take them into account: https://arxiv.org/abs/1906.03711. At the moment, all the pairwise comparison aggregation methods in Crowd-Kit do not handle possible item features.
