### ISSUE TITLE
Renamed columns?

### ISSUE THREAD

**Issue by jcklie** [Toloka/crowd-kit#15]
Hi,
the guide says 

   df = pd.read_csv('results.csv')  # should contain columns: task, performer, label

but when I load this file, then the second column is `worker` and not `performer`. I had used crowdkit with dataframes that had columns: task, performer, label, but after an update, it broke.

**Comment by btseytlin** [comment]
Hello.
We will update the guide, thank you.

The last update indeed introduced the non-backward-compatible renaming:
https://github.com/Toloka/crowd-kit/releases/tag/v1.0.0

It was done to remove some ambiguity and make the naming more in line with commonly used terms.

**Comment by dustalov** [comment]
@jcklie could you please confirm that the updated version of Crowd-Kit solved the issue?
