### ISSUE TITLE
[BUG]  Wrong columns names in crowd speech dataset

### ISSUE THREAD

**Issue by Senarect** [Toloka/crowd-kit#60]
### Observed behavior

I was using crowd speech dataset from crowd-kit and wanted to implement some aggravation methods and it found out that function fit_predict worked with only the columns named 'task', 'worker', 'output' but in this dataset their names new 'task', 'performer', 'text'. So I got the error that worker and output were not in the index.

### Expected behavior

Nikita Pavlichenko suggested me to create this issue to change the names of the columns in the dataset

### Python Version

3.7

### Crowd-Kit Version

1.0.0

### Example code

```Python
from crowdkit.datasets import load_dataset
from crowdkit.aggregation import TextHRRASA
from sentence_transformers import SentenceTransformer
encoder = SentenceTransformer('all-mpnet-base-v2')
hrrasa = TextHRRASA(encoder=encoder.encode)
df, gt = load_dataset('crowdspeech-test-clean')
df['text'] = df['text'].apply(lambda s: s.lower())
result = hrrasa.fit_predict(df)
```

**Comment by dustalov** [comment]
Hi, thank you for reporting this! I can confirm it is a bug.

The `load_crowdspeech_dataframes()` method does not renames the corresponding fields: https://github.com/Toloka/crowd-kit/blob/main/crowdkit/datasets/_loaders.py#L84 

You can work around this bug by manually renaming the `performer` column to the `worker` column and `text` to `output`.

Also, please add the title to this reported issue.

**Comment by pilot7747** [comment]
@dustalov I maybe blind but I see
`labels = pd.read_csv(join(data_path, 'crowd_labels.csv')).rename(columns={'output': 'text', 'performer': 'worker'})`

Seems like fields names must be correct.

**Comment by pilot7747** [comment]
@Senarect I checked on my machine an on `crowdkit==1.2.0` everything seems correct. 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/4653896/226450892-2c0edf91-d906-4e40-9df3-0407888e9996.png">

**Comment by pilot7747** [comment]
@Senarect Pls update the Crowd-Kit and inform us if the issue still appears.

**Comment by dustalov** [comment]
@pilot7747 @Senarect I think I understand the confusion.

In CrowdSpeech currently we have `task`, `worker`, and `text` columns. However, some implementation of our algorithms for textual aggregation require `output` column, some require `text` column, see https://github.com/Toloka/crowd-kit/issues/61.

If we should keep `text`, please close this issue.

**Comment by pilot7747** [comment]
Closing the issue in favour of fixing the bug in #61
