### ISSUE TITLE
[BUG] The ROVER from crowd-kit expects wrong column name

### ISSUE THREAD

**Issue by Senarect** [Toloka/crowd-kit#61]
### Observed behavior

I was using the ROVER for the textual responses aggregation and found out that ROVER expected the column named 'text'. It's very suspicious because the analogs like TextRASA and TextHRRASA expect the column named 'output'.

### Expected behavior

I suggest to unify functions' input. Use 'output' name for an example.

### Python Version

3.7

### Crowd-Kit Version

1.0.0

### Example code

```Python
from crowdkit.aggregation import load_dataset
from crowdkit.aggregation import ROVER

df, gt = load_dataset('crowdspeech-test-clean')
df['text'] = df['text'].apply(lambda s: s.lower())
df=df.rename(columns={'performer': 'worker'})
df=df.rename(columns={'text': 'output'})

tokenizer = lambda s: s.split(' ')
detokenizer = lambda tokens: ' '.join(tokens)
result = ROVER(tokenizer, detokenizer).fit_predict(df)
```

**Comment by dustalov** [comment]
- ROVER wants `text`: https://github.com/Toloka/crowd-kit/blob/main/crowdkit/aggregation/texts/rover.py
- RASA wants `output`: https://github.com/Toloka/crowd-kit/blob/main/crowdkit/aggregation/texts/text_rasa.py
- HRRASA wants `output`: https://github.com/Toloka/crowd-kit/blob/main/crowdkit/aggregation/texts/text_hrrasa.py
- TextSummarization wants `text`: https://github.com/Toloka/crowd-kit/blob/main/crowdkit/learning/text_summarization.py

**Comment by dustalov** [comment]
Yes.

**Comment by dustalov** [comment]
(And we need to check the dataset loaders.)

**Comment by pilot7747** [comment]
@Senarect pls check if #68 resolved this issue

**Comment by Senarect** [comment]
TextRASA and TextHRRASA still want ['output']

**Comment by pilot7747** [comment]
Please check on the GitHub version, we didn't make a new pypi release

**Comment by dustalov** [comment]
https://github.com/Toloka/crowd-kit/pull/69 please approve and I'll push the new version to PyPI

**Comment by dustalov** [comment]
Done, please update Crowd-Kit.
